-- Paste this into the Supabase SQL Editor.
-- This creates the Attendance Payroll schema in PostgreSQL.
-- RLS is enabled on all tables, with no public policies by default.

create table if not exists public.employees
(
    employeeid integer generated by default as identity primary key,
    employeecode varchar(20) not null unique,
    fullname varchar(150) not null,
    email varchar(150),
    phone varchar(50),
    position varchar(100),
    department varchar(100),
    hourlyrate numeric(18, 2) not null,
    hiredate date not null,
    isactive boolean not null default true,
    profileimage bytea,
    biometrictemplate bytea
);

create table if not exists public.attendancerecords
(
    attendanceid integer generated by default as identity primary key,
    employeeid integer not null references public.employees(employeeid),
    attendancedate date not null,
    timein timestamp without time zone,
    timeout timestamp without time zone,
    status varchar(30) not null default 'Present',
    isbiometricverified boolean not null default false,
    constraint uq_attendance_employeedate unique (employeeid, attendancedate)
);

create table if not exists public.payrollrecords
(
    payrollid integer generated by default as identity primary key,
    employeeid integer not null references public.employees(employeeid),
    payperiodstart date not null,
    payperiodend date not null,
    regularhours numeric(10, 2) not null,
    overtimehours numeric(10, 2) not null,
    grosspay numeric(18, 2) not null,
    deductions numeric(18, 2) not null,
    netpay numeric(18, 2) not null,
    status varchar(30) not null default 'Pending',
    createdat timestamp with time zone not null default timezone('utc', now())
);

create table if not exists public.useraccounts
(
    useraccountid integer generated by default as identity primary key,
    username varchar(80) not null unique,
    passwordhash varchar(256) not null,
    passwordsalt bytea,
    hashiterations integer not null default 210000,
    role varchar(20) not null,
    employeeid integer unique references public.employees(employeeid) on delete cascade,
    isactive boolean not null default true,
    createdat timestamp with time zone not null default timezone('utc', now())
);

create index if not exists idx_attendancerecords_employeeid on public.attendancerecords(employeeid);
create index if not exists idx_payrollrecords_employeeid on public.payrollrecords(employeeid);
create index if not exists idx_useraccounts_role on public.useraccounts(role);

alter table public.employees enable row level security;
alter table public.attendancerecords enable row level security;
alter table public.payrollrecords enable row level security;
alter table public.useraccounts enable row level security;

comment on table public.employees is 'Attendance Payroll employees.';
comment on table public.attendancerecords is 'Daily attendance logs.';
comment on table public.payrollrecords is 'Payroll records by pay period.';
comment on table public.useraccounts is 'Local app credentials. Add policies only after Supabase Auth and RLS rules are defined.';
